---

- name: "Collect subdirectories for {{ project_name }}"
  ansible.builtin.find:
    paths: "{{ directory.stat.path }}/"
    recurse: true
    file_type: "directory"
  delegate_to: "localhost"
  register: files_subdirs

- name: "Deploy subdirectories for {{ project_name }}"
  ansible.builtin.file:
    path: "{{ project_dir + '/' + file.path.split(project_name + '/')[1:] | join(project_name + '/') }}"
    mode: "{{ docker_directory_mode if not \
      (project_dir + '/' + file.path.split(project_name + '/')[1:] | join(project_name + '/')) | any_regex_matches(regex_secret_remote_paths) \
      else docker_secret_directory_mode }}"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
    state: "directory"
  with_list: "{{ files_subdirs.files }}"
  loop_control:
    loop_var: file
  notify: ["Restart project"]

- name: "Collect all files in directory"
  ansible.builtin.find:
    paths: "{{ directory.stat.path }}/"
    recurse: true
    file_type: "file"
    hidden: true
  delegate_to: "localhost"
  register: directory_files

- name: "Deploy files or templates for {{ project_name }}"
  ansible.builtin.include_tasks: "deploy_file.yml"
  with_list: "{{ directory_files.files }}"
  loop_control:
    loop_var: "file"

...
