---

- name: Handle deprecations
  ansible.builtin.include_tasks: "handle_deprecations.yml"

- name: Ensure correct python requirements are installed on hosts
  when: project_deployment_install_python_requirements
  become_user: "{{ project_deployment_docker_user }}"
  become: true
  block:
    - name: Install pip
      ansible.builtin.package:
        name: "python3-pip"
        state: present
    - name: Uninstall docker-py
      ansible.builtin.pip:
        name: "docker-py"
        state: absent
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Install python requirements
      ansible.builtin.pip:
        name: "docker"
        state: present
      ignore_errors: "{{ ansible_check_mode }}"

# This loops over all projects defined in the project_deployment_projects variable.
# Every project is handed to the deploy_project tasks-file,
# which deploys, updates and, if necessary, restarts the project
- name: Install all projects in project_deployment_projects
  ansible.builtin.include_tasks: "deploy_project.yml"
  vars:
    current_project: "{{ project }}"
  when: "project_deployment_projects_to_deploy|length==0 or project.key in project_deployment_projects_to_deploy"
  with_dict: "{{ project_deployment_projects }}"
  loop_control:
    loop_var: "project"

...
