---

- name: "Stop project"
  community.docker.docker_compose_v2:
    project_src: "{{ project_deployment_base_path }}/{{ project_name }}"
    remove_orphans: true
    state: absent
  become_user: "{{ project_deployment_docker_user }}"
  become: true

- name: "Start project"
  community.docker.docker_compose_v2:
    project_src: "{{ project_deployment_base_path }}/{{ project_name }}"
    state: present
  become_user: "{{ project_deployment_docker_user }}"
  become: true

...
