---

- name: "Stop project"
  community.docker.docker_compose_v2:
    project_src: "{{ project_deployment_base_path }}/{{ project_deployment_project_name }}"
    remove_orphans: true
    state: absent
  become_user: "{{ project_deployment_docker_user }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"  # the directory might not exist
  # TODO: add a nicer check for the directory existence

- name: "Start project"
  community.docker.docker_compose_v2:
    project_src: "{{ project_deployment_base_path }}/{{ project_deployment_project_name }}"
    state: present
  become_user: "{{ project_deployment_docker_user }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"  # the directory might not exist
  # TODO: add a nicer check for the directory existence

...
